---
name: setup
description: Sets up environment for project
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Setup node
      uses: actions/setup-node@v6
      with:
        node-version: 24

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Install dependencies
      shell: bash
      run: pnpm i --frozen-lockfile
