---
name: Check and test

on:
  push:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Run checks
        run: pnpm check
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Install chromium
        run: pnpm playwright install chromium

      - name: Run tests
        run: pnpm test

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          path: test/.results
          include-hidden-files: true
