---
name: Check and test

on:
  push:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup

      - name: Run checks
        run: pnpm check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup

      - name: Install chromium
        run: pnpm playwright install chromium

      - name: Run tests
        run: pnpm test
