---
name: Check and test

on:
  push:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup mise
        uses: jdx/mise-action@v4

      - name: Run ci checks
        run: mise ci
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup mise
        uses: jdx/mise-action@v4

      - name: Run tests
        run: mise test

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: test-results
          path: test/.results
          include-hidden-files: true
